name: get-megdata-tests
on: [push]
jobs:
  Pytest:
    name: InstallAndTest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]
    steps:
      - uses: conda-incubator/setup-miniconda@v3
      - uses: actions/checkout@v4
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install Python and Pytest
        shell: bash -el {0}
        run: conda install --override-channels --channel=conda-forge 'python<3.12' pytest pip  
      - name: Install Git
        run: sudo apt install git -y
      - name: Pip Install megcore-getdata
        shell: bash -el {0}
        run: $CONDA/bin/pip install git+https://github.com/nih-megcore/megcore-getdata.git
      - name: Pytest
        shell: bash -el {0}
        run: $CONDA/bin/python -m pytest
  
