name: get-megdata-tests
on: [push]
jobs:
  Pytest:
    name: InstallAndTest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python and Pytest
        shell: bash -el {0}
        run: sudo apt install python git -y  
      - name: Pip install pytest
        run: python -m pip install pytest 
      - name: Pip Install megcore-getdata
        shell: bash -el {0}
        run: python -m pip install git+https://github.com/nih-megcore/megcore-getdata.git
      - name: Pytest
        shell: bash -el {0}
        run: pytest
  
